language: ruby
script: script/test
cache:
  bundler: true
  directories:
    - vendor/bundle
env:
  matrix:
    - JEKYLL_VERSION=3.1
    - JEKYLL_VERSION=3.2
    - JEKYLL_VERSION=3.3
    - JEKYLL_VERSION=3.4
    - JEKYLL_VERSION=3.5
    - JEKYLL_VERSION=3.6
    - LINTING=true
rvm:
  - 2.5
  - 2.4
branches:
  only:
    - master
